# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8256ef32188f78a839b7ae0a0f83b5e689c705346784bd5c6cb12af0f7bcfb7faef69b1aa9541742d9537b6a27857df356d571517efaeeef799913ea08822f8d

test:
  secret_key_base: 4f115461a37bad791e2e77b07294e73a2a5d2af57598b258ed93e2021053e469d9c65b97d37b44bf6002f3316a942b85730245e344ad623945563c20d23a9cd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
