# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 687a920d56d11e615de3a07e5f0c0ff6c40ef98659fc33d8cad112298dfdcc44a66b22e81d328acae0dacff068db9a020cf8085054cfb692dec4e994d61829d6

test:
  secret_key_base: 5b915e854f32c20354e40ef67892ce96ef8170a708ef10b0c18eb02e62e08b09a81ba12d2677bc4e2efcb87846fdfe4335646fb16e26758c6af72f6ad6e9266a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
